#!/bin/bash
# ushare         This shell script takes care of starting and stopping
#               ushare
#
# chkconfig: 2345 65 35
# description: ushare is UPnP (TM) A/V Media Server.
#
# processname: ushare
# config: /etc/ushare.conf
# pid /var/run/ushare.pid

# Source function library.
. /etc/rc.d/init.d/functions

DAEMON=/usr/bin/ushare
NAME=ushare
DESC="uShare UPnP A/V Media Server"
PIDFILE=/var/run/ushare.pid

[ -r "/etc/ushare.conf" ] && . /etc/ushare.conf

# abort if no executable exists
[ -x $DAEMON ] || exit 0

# abort if no shared directory is defined
[ -z "$USHARE_DIR" ] && exit 0

set -e

case "$1" in
  start)
    gprintf "Starting $DESC : "
    $DAEMON -D --cfg=/etc/ushare.conf -d
    RETVAL=$?
    echo
   [ $RETVAL -eq 0 ] && touch $PIDFILE
   exit $RETVAL
   ;;
  stop)
   gprintf "Stopping $DESC : "
   killall $DAEMON 2>/dev/null
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && rm -f $PIDFILE
   exit $RETVAL
  ;;
  reload)
  killall -1 $DAEMON
  ;;
  restart)
    $0 stop
    $1 start
  ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    exit 2
  ;;
esac

exit 0
